on:
  issue_comment:
    types: [created]

jobs:
  move-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.TOKEN }}" | gh auth login --with-token

      - name: Check GitHub CLI Authentication
        run: gh auth status

      # Optional: Fetch all projects for debugging (if needed)
      - name: Debug Project List
        run: |
          gh project list --format json | jq

      - name: Get Project Number
        id: get_project
        run: |
          PROJECT_NUMBER="PVT_kwHOCtxfb84Asjcz"
          if [[ -z "$PROJECT_NUMBER" ]]; then
            echo "Error: Project 'New_Project' not found!"
            exit 1
          fi
          echo "PROJECT_NUMBER=${PROJECT_NUMBER}" >> $GITHUB_ENV

      - name: Get Issue URL
        id: get_issue
        run: |
          ISSUE_URL=$(gh issue view "${{ github.event.issue.number }}" --json url | jq -r '.url')
          if [[ -z "$ISSUE_URL" ]]; then
            echo "Error: Unable to fetch issue URL!"
            exit 1
          fi
          echo "ISSUE_URL=${ISSUE_URL}" >> $GITHUB_ENV

      - name: Debug Outputs
        run: |
          echo "Project Number: ${{ env.PROJECT_NUMBER }}"
          echo "Issue URL: ${{ env.ISSUE_URL }}"
