name: Java CI with Maven

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  # Test job: Runs unit tests and reports results
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        
    runs-on: ${{matrix.platform}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'
      - name: List files
        run: ls -R
      - name: Build with Maven
        run: mvn clean install
        working-directory: ./demo
      - name: Run tests
        run: mvn -f ./demo/pom.xml test
        
      - name: Run code quality checks with Maven
        run: mvn -f ./demo/pom.xml checkstyle:check
        continue-on-error: true  # Allows workflow to continue if checkstyle fails
      
      - name: Generate test coverage report
        run: mvn -f ./demo/pom.xml jacoco:report
