name: Move Issues on Kanban Based on Comments
 
on:
  issue_comment:
    types:
      - created
 
jobs:
  move-issues:
    runs-on: ubuntu-latest

    env:
      ACTIONS_STEP_DEBUG: true  # Enable detailed debug logs
 
    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3
 
    # Step 2: List all projects for debugging
    - name: List projects
      run: gh project list
      env:
        GH_TOKEN: ${{ secrets.token }}
 
    - name: Debug Project Information
      run: gh project view 7 --format json --owner "@me" | jq -r '.[]'
      env:
        GH_TOKEN: ${{ secrets.token }}
 
 
    # Step 3: Move issues based on comment content (Done)
    - name: Move Issues on Kanban
      uses: leonsteinhaeuser/project-beta-automations@v2.1.0
      if: ${{ github.event_name == 'issue_comment' && github.event.action == 'created' && contains(github.event.comment.body, 'Done') }}
      with:
         gh_token: ${{ secrets.token }}
         project_id: 7
         user: 'Vinod-421'
         resource_node_id: ${{ github.event.issue.node_id }}  # Use the node_id from the issue
         move_related_issues: true
         status_value: 'Done' # Target status

     # Step 4: Move issues based on comment content (In Progress)
    - name: Move Issues on Kanban
      uses: leonsteinhaeuser/project-beta-automations@v2.1.0
      if: ${{ github.event_name == 'issue_comment' && github.event.action == 'created' && contains(github.event.comment.body, 'In Progress') }}
      with:
         gh_token: ${{ secrets.token }}
         project_id: 7
         user: 'Vinod-421'
         resource_node_id: ${{ github.event.issue.node_id }}  # Use the node_id from the issue
         move_related_issues: true
         status_value: 'In Progress' # Target status
